Revert "Revert "[TTS] Add new deps for TTS testing (#62671)"" (#64479)
Reverts [Internal link]

```
ModuleNotFoundError: DNSMOS metric requires that librosa, onnxruntime and requests are installed. Install as `pip install librosa onnxruntime-gpu requests`.
[2025-06-26 17:20:18] ERROR 437 Thread-2 (_run_async_worker) zmq_queue.py:266: Failed to receive message on ZMQ socket for unknown reason: Socket operation on non-socket
```
MODULAR_ORIG_COMMIT_REV_ID: e840f1f3c51f73280b73da69ac806d122bab94df