Revert "[SDK] Use rmo.conv in conv2d and conv3d" (#59550)
Breaks shape inference for pixtral: `br
//SDK/integration-test/pipelines/python:verify_pipelines -- --pipeline
pixtral-bfloat16 --devices gpu`

returns:
```
ValueError: Failed to create op 'conv':
Inputs:
    input = TensorValue(dtype=bfloat16, shape=[Dim(1), Dim('image_height'), Dim('image_width'), Dim('num_channels')], device=None)
    filter = TensorValue(dtype=bfloat16, shape=[Dim(16), Dim(16), Dim(3), Dim(1024)], device=None)
    strides = Attribute(#mosh<ape[16, 16]> : !mosh.ape)
    dilations = Attribute(#mosh<ape[1, 1]> : !mosh.ape)
    paddings = Attribute(#mosh<ape[0, 0, 0, 0]> : !mosh.ape)
    num_groups = 1

Diagnostics:
    [convolution] requires (input_channels == num_groups * filter_channels)
Operation creation failed
```

Reverts [Internal link]

MAX_GRAPH_API_ORIG_REV_ID: cb837a350a8145907bfbc454582dfbe635fc4b87