[CI] [Bazel] Disable remote caching for now (#61705)
[External] [CI] Remove use of `--remote-header` in new Bazel job

The `BUILDBUDDY_TOKEN` secret is only available to Modular employees
part of the new org we set up for public CI. However, this means when we
always specify `--remote_header=$BUILDBUDDY_TOKEN`, it will expand to an
empty value for non-Modular folks. This creates a parsing error and the
job never runs.

Workaround this for now by just removing the `remote_header`. There's
other things we need to figure out if we explore remote builds and
caching for non-Modular contributors. This unblocks the job from being
experimented with in the non-Modular contributor case.

Uploading will still fail even with this change, but we can figure that
out after this lands:

```
ERROR: The Build Event Protocol upload failed: Not retrying publishBuildEvents, no more attempts left: status='Status{code=PERMISSION_DENIED, description=Anonymous access disabled, permission denied., cause=null}' PERMISSION_DENIED: PERMISSION_DENIED: Anonymous access disabled, permission denied. PERMISSION_DENIED: PERMISSION_DENIED: Anonymous access disabled, permission denied.
```

<!--
Thanks for submitting a pull request,
your contribution is really appreciated!

If possible, add a link to the issue you are
trying to solve in the pull request description.

If your pull request is big (> 100 lines), consider splitting it
into multiple pull requests as it may accelerate the review process.
-->

Co-authored-by: Joe Loser <joeloser@fastmail.com>
Closes modular/modular#4550
MODULAR_ORIG_COMMIT_REV_ID: a97dbd8be4c75f4e5aa0171ba8d85cbe1cb06f5f