[SDK] Fix `chunk.is_done` in AudioGeneratorPipeline
Fix a check for `chunk.is_done` in `AudioGeneratorPipeline`.
Previously this was calling `.is_done` on a driver `Tensor`, causing an
attribute error:

```python
AttributeError: 'Tensor' object has no attribute 'is_done'. Did you mean: 'is_conj'?
```
MODULAR_ORIG_COMMIT_REV_ID: 2b3b19dba28db6a703ad3d61c152a7f0a74cfc19